import { RetrievalMode } from '@/store/app-context';
import { UserRole, EmployeeProfile, PersonaConfig, WorkspaceManifest } from '@/lib/types';

export const PERSONA_PROFILE_TEMPLATES: Record<string, EmployeeProfile & { personaRole: UserRole; permissions: string[] }> = {
  'ravi.kumar@company.com': {
    employeeId: 'EMP-2041',
    name: 'Ravi Kumar',
    email: 'ravi.kumar@company.com',
    department: 'Operations',
    designation: 'Lead Field Technician',
    personaRole: 'Field Technician',
    permissions: ['chat', 'history', 'transparency'],
  },
  'priya.sharma@company.com': {
    employeeId: 'EMP-1024',
    name: 'Priya Sharma',
    email: 'priya.sharma@company.com',
    department: 'Maintenance',
    designation: 'Senior Maintenance Engineer',
    personaRole: 'Maintenance Engineer',
    permissions: ['chat', 'upload', 'processing', 'history', 'transparency'],
  },
  'arjun.mehta@company.com': {
    employeeId: 'EMP-3092',
    name: 'Arjun Mehta',
    email: 'arjun.mehta@company.com',
    department: 'Projects',
    designation: 'Technical Project Manager',
    personaRole: 'Project Manager',
    permissions: ['chat', 'history', 'transparency'],
  },
  'neha.iyer@company.com': {
    employeeId: 'EMP-4401',
    name: 'Neha Iyer',
    email: 'neha.iyer@company.com',
    department: 'Quality Assurance & Compliance',
    designation: 'Corporate Compliance Manager',
    personaRole: 'Regulatory & Compliance Manager',
    permissions: ['history', 'transparency', 'audit'],
  },
  'vikram.rao@company.com': {
    employeeId: 'EMP-0010',
    name: 'Vikram Rao',
    email: 'vikram.rao@company.com',
    department: 'Executive Board',
    designation: 'Director of Plant Operations',
    personaRole: 'Director / Executive',
    permissions: ['chat', 'history', 'transparency', 'audit'],
  },
  'cherry@company.com': {
    employeeId: 'EMP-1001',
    name: 'Cherry',
    email: 'cherry@company.com',
    department: 'Executive Operations',
    designation: 'General Operations Manager',
    personaRole: 'Director / Executive',
    permissions: ['chat', 'upload', 'processing', 'history', 'transparency', 'audit'],
  },
  'cherry.jai@company.com': {
    employeeId: 'EMP-1002',
    name: 'Cherry Jai',
    email: 'cherry.jai@company.com',
    department: 'Executive Operations',
    designation: 'General Operations Manager',
    personaRole: 'Director / Executive',
    permissions: ['chat', 'upload', 'processing', 'history', 'transparency', 'audit'],
  },
};

export const PERSONA_CONFIGS: Record<UserRole, PersonaConfig> = {
  'Field Technician': {
    role: 'Field Technician',
    defaultLandingWorkspace: '/dashboard',
    defaultRetrievalMode: 'automatic',
    permissions: ['chat', 'history', 'transparency'],
    dashboardWidgets: ['assigned-equipment', 'recent-repairs', 'safety-alerts', 'equipment-history', 'recent-uploads', 'my-requests'],
    quickActions: [
      { label: 'View Repair Procedure', actionUrl: '/chat', isPlaceholder: true },
      { label: 'Equipment History Logs', actionUrl: '/history' },
      { label: 'Safety Guidelines Checklist', actionUrl: '/chat', isPlaceholder: true },
    ],
    chatStarters: [
      'Show repair procedure for Boiler Cylinder B-3',
      'What is the equipment safety check for Loop-A?',
      'Check maintenance history logs on SV-901',
    ],
    transparencyFocus: 'Safety standards, operation checklists, blueprint schematics, and operator manuals.',
    sidebarNav: [
      { label: 'Dashboard', path: '/dashboard', icon: 'LayoutDashboard' },
      { label: 'AI Chat', path: '/chat', icon: 'MessageSquare' },
      { label: 'History', path: '/history', icon: 'History' },
    ],
  },
  'Maintenance Engineer': {
    role: 'Maintenance Engineer',
    defaultLandingWorkspace: '/dashboard',
    defaultRetrievalMode: 'automatic',
    permissions: ['chat', 'upload', 'processing', 'history', 'transparency'],
    dashboardWidgets: ['failure-trends', 'maintenance-schedule', 'uploaded-manuals', 'processing-queue', 'recent-uploads', 'my-requests'],
    quickActions: [
      { label: 'Failure Analysis Review', actionUrl: '/transparency' },
      { label: 'Inspection Log entries', actionUrl: '/history' },
      { label: 'Ingest OEM Manual', actionUrl: '/upload' },
      { label: 'Maintenance Schedule', actionUrl: '/chat', isPlaceholder: true },
    ],
    chatStarters: [
      'Analyze root cause for Cylinder B-3 error codes',
      'Verify last failure schedule on primary loops',
      'Search OEM manual specs for turbine valve calibration',
    ],
    transparencyFocus: 'Root cause resolution, entity relations, processing indexes, and full pipeline chronologies.',
    sidebarNav: [
      { label: 'Dashboard', path: '/dashboard', icon: 'LayoutDashboard' },
      { label: 'Upload Files', path: '/upload', icon: 'UploadCloud' },
      { label: 'AI Processing', path: '/processing', icon: 'Cpu' },
      { label: 'AI Chat', path: '/chat', icon: 'MessageSquare' },
      { label: 'RAG Audit', path: '/transparency', icon: 'Eye' },
      { label: 'History', path: '/history', icon: 'History' },
    ],
  },
  'Project Manager': {
    role: 'Project Manager',
    defaultLandingWorkspace: '/dashboard',
    defaultRetrievalMode: 'automatic',
    permissions: ['chat', 'history', 'transparency'],
    dashboardWidgets: ['project-status', 'team-progress', 'project-delays', 'resource-allocation', 'recent-uploads', 'my-requests'],
    quickActions: [
      { label: 'Project Progress Tracker', actionUrl: '/history' },
      { label: 'Resource Allocation table', actionUrl: '/chat', isPlaceholder: true },
      { label: 'Weekly Summary Reports', actionUrl: '/chat', isPlaceholder: true },
      { label: 'Risk Heatmap audit', actionUrl: '/transparency' },
    ],
    chatStarters: [
      'What is the current project progress on Reactor Loop Q3?',
      'Check operational resource allocation constraints',
      'Summarize safety delays reported this week',
    ],
    transparencyFocus: 'Milestone dependencies, project schedules, metadata summary tags, and team progress metrics.',
    sidebarNav: [
      { label: 'Dashboard', path: '/dashboard', icon: 'LayoutDashboard' },
      { label: 'AI Chat', path: '/chat', icon: 'MessageSquare' },
      { label: 'RAG Audit', path: '/transparency', icon: 'Eye' },
      { label: 'History', path: '/history', icon: 'History' },
    ],
  },
  'Regulatory & Compliance Manager': {
    role: 'Regulatory & Compliance Manager',
    defaultLandingWorkspace: '/dashboard',
    defaultRetrievalMode: 'manual',
    permissions: ['history', 'transparency', 'audit'],
    dashboardWidgets: ['pending-audits', 'compliance-status', 'access-requests', 'transparency-reviews', 'recent-uploads'],
    quickActions: [
      { label: 'Pending Compliance Audits', actionUrl: '/audit' },
      { label: 'Compliance Policy Checklist', actionUrl: '/transparency' },
      { label: 'Identify Missing Evidence Chunks', actionUrl: '/history' },
      { label: 'Access Requests queues', actionUrl: '/audit' },
    ],
    chatStarters: [
      'Verify steam venting compliance guidelines OSHA 1910.111',
      'Review missing safety evidence for Cylinder B-3',
      'List regulatory requirements active for Reactor Unit 5',
    ],
    transparencyFocus: 'Trace citation page intervals, verification standards, access permissions, and audit logs.',
    sidebarNav: [
      { label: 'Dashboard', path: '/dashboard', icon: 'LayoutDashboard' },
      { label: 'RAG Audit', path: '/transparency', icon: 'Eye' },
      { label: 'Audit Logs', path: '/audit', icon: 'ShieldCheck' },
      { label: 'History', path: '/history', icon: 'History' },
    ],
  },
  'Director / Executive': {
    role: 'Director / Executive',
    defaultLandingWorkspace: '/dashboard',
    defaultRetrievalMode: 'automatic',
    permissions: ['chat', 'history', 'transparency', 'audit'],
    dashboardWidgets: ['org-kpis', 'downtime-trends', 'ai-usage-analytics', 'risk-heatmap', 'knowledge-coverage', 'recent-uploads', 'access-requests'],
    quickActions: [
      { label: 'Executive Operations Summary', actionUrl: '/chat', isPlaceholder: true },
      { label: 'Operational Risk profiles', actionUrl: '/audit' },
      { label: 'Downtime Trend analysis', actionUrl: '/transparency' },
      { label: 'Organization Insights dashboards', actionUrl: '/history' },
    ],
    chatStarters: [
      'Summarize top operational risks across active plants',
      'Analyze downtime trends reported on Boiler 092',
      'Show organization KPIs and knowledge coverage metrics',
    ],
    transparencyFocus: 'Business impact metrics, executive decisions, operational risk layers, and recommendations.',
    sidebarNav: [
      { label: 'Dashboard', path: '/dashboard', icon: 'LayoutDashboard' },
      { label: 'AI Chat', path: '/chat', icon: 'MessageSquare' },
      { label: 'RAG Audit', path: '/transparency', icon: 'Eye' },
      { label: 'Audit Logs', path: '/audit', icon: 'ShieldCheck' },
      { label: 'History', path: '/history', icon: 'History' },
    ],
  },
};
